/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: grxNYctbMek6PL66cujx3u
// Component: cy-CLI21vlSG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Paziresh24MultilineTextInput from "../../Paziresh24MultilineTextInput"; // plasmic-import: 5O8XqcSJJk6J/component
import Paziresh24Button from "../../Paziresh24Button"; // plasmic-import: YOhw5fIQJQgB/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: grxNYctbMek6PL66cujx3u/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: grxNYctbMek6PL66cujx3u/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: grxNYctbMek6PL66cujx3u/projectcss
import sty from "./PlasmicLauncherBlocksWriteReply.module.css"; // plasmic-import: cy-CLI21vlSG/css

import ChevronRightIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronRight"; // plasmic-import: 0359howWu0cr/icon
import ChevronLeftIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: jS0YlkKPLO7U/icon

createPlasmicElementProxy;

export type PlasmicLauncherBlocksWriteReply__VariantMembers = {
  instance: "instance";
};
export type PlasmicLauncherBlocksWriteReply__VariantsArgs = {
  instance?: SingleBooleanChoiceArg<"instance">;
};
type VariantPropType = keyof PlasmicLauncherBlocksWriteReply__VariantsArgs;
export const PlasmicLauncherBlocksWriteReply__VariantProps =
  new Array<VariantPropType>("instance");

export type PlasmicLauncherBlocksWriteReply__ArgsType = {
  appKey?: string;
  onSubmit?: () => void;
  reviewId?: string;
};
type ArgPropType = keyof PlasmicLauncherBlocksWriteReply__ArgsType;
export const PlasmicLauncherBlocksWriteReply__ArgProps = new Array<ArgPropType>(
  "appKey",
  "onSubmit",
  "reviewId"
);

export type PlasmicLauncherBlocksWriteReply__OverridesType = {
  root?: Flex__<"div">;
  multilineTextInput?: Flex__<typeof Paziresh24MultilineTextInput>;
  freeBox?: Flex__<"div">;
  paziresh24Button?: Flex__<typeof Paziresh24Button>;
};

export interface DefaultLauncherBlocksWriteReplyProps {
  appKey?: string;
  onSubmit?: () => void;
  reviewId?: string;
  instance?: SingleBooleanChoiceArg<"instance">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLauncherBlocksWriteReply__RenderFunc(props: {
  variants: PlasmicLauncherBlocksWriteReply__VariantsArgs;
  args: PlasmicLauncherBlocksWriteReply__ArgsType;
  overrides: PlasmicLauncherBlocksWriteReply__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "multilineTextInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "instance",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.instance
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootinstance]: hasVariant($state, "instance", "instance") }
      )}
    >
      <Paziresh24MultilineTextInput
        data-plasmic-name={"multilineTextInput"}
        data-plasmic-override={overrides.multilineTextInput}
        autoSize={true}
        className={classNames("__wab_instance", sty.multilineTextInput, {
          [sty.multilineTextInputinstance]: hasVariant(
            $state,
            "instance",
            "instance"
          )
        })}
        onValueChange={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, [
            "multilineTextInput",
            "value"
          ]).apply(null, eventArgs);

          if (
            eventArgs.length > 1 &&
            eventArgs[1] &&
            eventArgs[1]._plasmic_state_init_
          ) {
            return;
          }
        }}
        placeholder={
          "\u0646\u0638\u0631\u062e\u0648\u062f \u0631\u0627 \u0628\u0646\u0648\u06cc\u0633\u06cc\u062f"
        }
        value={generateStateValueProp($state, ["multilineTextInput", "value"])}
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxinstance]: hasVariant($state, "instance", "instance")
        })}
      >
        <Paziresh24Button
          data-plasmic-name={"paziresh24Button"}
          data-plasmic-override={overrides.paziresh24Button}
          children2={"\u0627\u0631\u0633\u0627\u0644 \u067e\u0627\u0633\u062e"}
          className={classNames("__wab_instance", sty.paziresh24Button)}
          isDisabled={(() => {
            try {
              return !$state.multilineTextInput?.value?.trim();
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          loading={(() => {
            try {
              return $state.loading;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          onClick={async event => {
            const $steps = {};

            $steps["updateLoading"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["loading"]
                    },
                    operation: 0,
                    value: true
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateLoading"] != null &&
              typeof $steps["updateLoading"] === "object" &&
              typeof $steps["updateLoading"].then === "function"
            ) {
              $steps["updateLoading"] = await $steps["updateLoading"];
            }

            $steps["invokeGlobalAction"] = true
              ? (() => {
                  const actionArgs = {
                    args: [
                      "POST",
                      (() => {
                        try {
                          return `https://apigw.paziresh24.com/v1/hamdast/apps/${$props.appKey}/reviews/${$props.reviewId}/replies`;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })(),
                      undefined,
                      (() => {
                        try {
                          return {
                            content: $state.multilineTextInput.value
                          };
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()
                    ]
                  };
                  return $globalActions["Fragment.apiRequest"]?.apply(null, [
                    ...actionArgs.args
                  ]);
                })()
              : undefined;
            if (
              $steps["invokeGlobalAction"] != null &&
              typeof $steps["invokeGlobalAction"] === "object" &&
              typeof $steps["invokeGlobalAction"].then === "function"
            ) {
              $steps["invokeGlobalAction"] = await $steps["invokeGlobalAction"];
            }

            $steps["updateLoading2"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["loading"]
                    },
                    operation: 0,
                    value: false
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateLoading2"] != null &&
              typeof $steps["updateLoading2"] === "object" &&
              typeof $steps["updateLoading2"].then === "function"
            ) {
              $steps["updateLoading2"] = await $steps["updateLoading2"];
            }

            $steps["runOnSubmit"] = true
              ? (() => {
                  const actionArgs = { eventRef: $props["onSubmit"] };
                  return (({ eventRef, args }) => {
                    return eventRef?.(...(args ?? []));
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["runOnSubmit"] != null &&
              typeof $steps["runOnSubmit"] === "object" &&
              typeof $steps["runOnSubmit"].then === "function"
            ) {
              $steps["runOnSubmit"] = await $steps["runOnSubmit"];
            }
          }}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "multilineTextInput", "freeBox", "paziresh24Button"],
  multilineTextInput: ["multilineTextInput"],
  freeBox: ["freeBox", "paziresh24Button"],
  paziresh24Button: ["paziresh24Button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  multilineTextInput: typeof Paziresh24MultilineTextInput;
  freeBox: "div";
  paziresh24Button: typeof Paziresh24Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLauncherBlocksWriteReply__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLauncherBlocksWriteReply__VariantsArgs;
    args?: PlasmicLauncherBlocksWriteReply__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLauncherBlocksWriteReply__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLauncherBlocksWriteReply__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLauncherBlocksWriteReply__ArgProps,
          internalVariantPropNames:
            PlasmicLauncherBlocksWriteReply__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLauncherBlocksWriteReply__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLauncherBlocksWriteReply";
  } else {
    func.displayName = `PlasmicLauncherBlocksWriteReply.${nodeName}`;
  }
  return func;
}

export const PlasmicLauncherBlocksWriteReply = Object.assign(
  // Top-level PlasmicLauncherBlocksWriteReply renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    multilineTextInput: makeNodeComponent("multilineTextInput"),
    freeBox: makeNodeComponent("freeBox"),
    paziresh24Button: makeNodeComponent("paziresh24Button"),

    // Metadata about props expected for PlasmicLauncherBlocksWriteReply
    internalVariantProps: PlasmicLauncherBlocksWriteReply__VariantProps,
    internalArgProps: PlasmicLauncherBlocksWriteReply__ArgProps
  }
);

export default PlasmicLauncherBlocksWriteReply;
/* prettier-ignore-end */
