/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: grxNYctbMek6PL66cujx3u
// Component: T_aUMqQUBscZ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Paziresh24Modal from "../../Paziresh24Modal"; // plasmic-import: ZGdhyEBPJSmH/component
import Paziresh24Button from "../../Paziresh24Button"; // plasmic-import: YOhw5fIQJQgB/component
import LauncherBlocksWriteReview from "../../LauncherBlocksWriteReview"; // plasmic-import: 3E3zip3yhAhO/component
import LauncherBlocksRateRow from "../../LauncherBlocksRateRow"; // plasmic-import: Ryf7wvUcVDQV/component
import { ApiRequest } from "@/common/fragment/components/api-request"; // plasmic-import: IpxudV5ARc89/codeComponent
import LauncherBlocksReviewCard from "../../LauncherBlocksReviewCard"; // plasmic-import: DrNNuC_MkTfg/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: grxNYctbMek6PL66cujx3u/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: grxNYctbMek6PL66cujx3u/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: grxNYctbMek6PL66cujx3u/projectcss
import sty from "./PlasmicLauncherBlocksRateReview.module.css"; // plasmic-import: T_aUMqQUBscZ/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: tltd2ahuz9sI/icon
import LauncherIconsEditIcon from "./icons/PlasmicIcon__LauncherIconsEdit"; // plasmic-import: GtRDVu6zRFVG/icon
import ChevronLeftIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronLeft"; // plasmic-import: jS0YlkKPLO7U/icon
import LauncherIconsLoaderIcon from "./icons/PlasmicIcon__LauncherIconsLoader"; // plasmic-import: 4lP5I8e4Rz71/icon
import ChevronRightIcon from "../paziresh_24_design_system/icons/PlasmicIcon__ChevronRight"; // plasmic-import: 0359howWu0cr/icon

createPlasmicElementProxy;

export type PlasmicLauncherBlocksRateReview__VariantMembers = {};
export type PlasmicLauncherBlocksRateReview__VariantsArgs = {};
type VariantPropType = keyof PlasmicLauncherBlocksRateReview__VariantsArgs;
export const PlasmicLauncherBlocksRateReview__VariantProps =
  new Array<VariantPropType>();

export type PlasmicLauncherBlocksRateReview__ArgsType = { appKey?: string };
type ArgPropType = keyof PlasmicLauncherBlocksRateReview__ArgsType;
export const PlasmicLauncherBlocksRateReview__ArgProps = new Array<ArgPropType>(
  "appKey"
);

export type PlasmicLauncherBlocksRateReview__OverridesType = {
  root?: Flex__<"div">;
  modal2?: Flex__<typeof Paziresh24Modal>;
  launcherBlocksWriteReview?: Flex__<typeof LauncherBlocksWriteReview>;
  launcherBlocksRateRow?: Flex__<typeof LauncherBlocksRateRow>;
  apiRequest4?: Flex__<typeof ApiRequest>;
  apiRequest3?: Flex__<typeof ApiRequest>;
  modal?: Flex__<typeof Paziresh24Modal>;
  span?: Flex__<"span">;
  strong?: Flex__<"strong">;
  apiRequest?: Flex__<typeof ApiRequest>;
};

export interface DefaultLauncherBlocksRateReviewProps {
  appKey?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLauncherBlocksRateReview__RenderFunc(props: {
  variants: PlasmicLauncherBlocksRateReview__VariantsArgs;
  args: PlasmicLauncherBlocksRateReview__ArgsType;
  overrides: PlasmicLauncherBlocksRateReview__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "apiRequest3.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest3"
      },
      {
        path: "apiRequest3.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest3"
      },
      {
        path: "apiRequest3.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest3"
      },
      {
        path: "apiRequest4.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest4"
      },
      {
        path: "apiRequest4.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest4"
      },
      {
        path: "apiRequest4.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest4"
      },
      {
        path: "modal.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "reviews",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => []
      },
      {
        path: "page",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 1
      },
      {
        path: "apiRequest.data",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.error",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "apiRequest.loading",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "apiRequest"
      },
      {
        path: "modal2.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
      id={"reviews"}
    >
      <div className={classNames(projectcss.all, sty.freeBox__w0Ud)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zlBGw
          )}
        >
          {
            "\u0646\u0638\u0631\u0627\u062a \u06a9\u0627\u0631\u0628\u0631\u0627\u0646"
          }
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__ebizj)}>
          <div className={classNames(projectcss.all, sty.freeBox___7Myos)}>
            <Icon4Icon
              className={classNames(projectcss.all, sty.svg__lFuH6)}
              role={"img"}
            />

            {(() => {
              try {
                return $state.apiRequest4.data?.count != undefined;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return false;
                }
                throw e;
              }
            })() ? (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zTUd
                )}
              >
                <React.Fragment>
                  {(() => {
                    try {
                      return $state.apiRequest4.data.average + " از 5 ";
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "";
                      }
                      throw e;
                    }
                  })()}
                </React.Fragment>
              </div>
            ) : null}
            {(() => {
              try {
                return $state.apiRequest4.data?.count == undefined;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return false;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__iVfQ)} />
            ) : null}
          </div>
          <Paziresh24Modal
            data-plasmic-name={"modal2"}
            data-plasmic-override={overrides.modal2}
            body={
              <LauncherBlocksWriteReview
                data-plasmic-name={"launcherBlocksWriteReview"}
                data-plasmic-override={overrides.launcherBlocksWriteReview}
                appKey={(() => {
                  try {
                    return $props.appKey;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                className={classNames(
                  "__wab_instance",
                  sty.launcherBlocksWriteReview
                )}
                onCancel={async () => {
                  const $steps = {};

                  $steps["updateModal2Open"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["modal2", "open"]
                          },
                          operation: 0,
                          value: false
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateModal2Open"] != null &&
                    typeof $steps["updateModal2Open"] === "object" &&
                    typeof $steps["updateModal2Open"].then === "function"
                  ) {
                    $steps["updateModal2Open"] = await $steps[
                      "updateModal2Open"
                    ];
                  }
                }}
                onSubmit={async () => {
                  const $steps = {};

                  $steps["updateModal2Open"] = true
                    ? (() => {
                        const actionArgs = {
                          variable: {
                            objRoot: $state,
                            variablePath: ["modal2", "open"]
                          },
                          operation: 0,
                          value: false
                        };
                        return (({
                          variable,
                          value,
                          startIndex,
                          deleteCount
                        }) => {
                          if (!variable) {
                            return;
                          }
                          const { objRoot, variablePath } = variable;

                          $stateSet(objRoot, variablePath, value);
                          return value;
                        })?.apply(null, [actionArgs]);
                      })()
                    : undefined;
                  if (
                    $steps["updateModal2Open"] != null &&
                    typeof $steps["updateModal2Open"] === "object" &&
                    typeof $steps["updateModal2Open"].then === "function"
                  ) {
                    $steps["updateModal2Open"] = await $steps[
                      "updateModal2Open"
                    ];
                  }

                  $steps["invokeGlobalAction"] = true
                    ? (() => {
                        const actionArgs = {
                          args: [
                            undefined,
                            "\u0646\u0638\u0631 \u0634\u0645\u0627 \u062b\u0628\u062a \u0634\u062f\u060c \u067e\u0633 \u0627\u0632 \u062a\u0627\u06cc\u06cc\u062f \u0646\u0645\u0627\u06cc\u0634 \u062f\u0627\u062f\u0647 \u062e\u0648\u0627\u0647\u062f \u0634\u062f.",
                            "top-center"
                          ]
                        };
                        return $globalActions["Fragment.showToast"]?.apply(
                          null,
                          [...actionArgs.args]
                        );
                      })()
                    : undefined;
                  if (
                    $steps["invokeGlobalAction"] != null &&
                    typeof $steps["invokeGlobalAction"] === "object" &&
                    typeof $steps["invokeGlobalAction"].then === "function"
                  ) {
                    $steps["invokeGlobalAction"] = await $steps[
                      "invokeGlobalAction"
                    ];
                  }
                }}
              />
            }
            className={classNames("__wab_instance", sty.modal2)}
            onOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["modal2", "open"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            open={generateStateValueProp($state, ["modal2", "open"])}
            title={
              "\u0646\u0638\u0631\u062a \u062f\u0631\u0628\u0627\u0631\u0647 \u0627\u06cc\u0646 \u0627\u0628\u0632\u0627\u0631\u06a9\r"
            }
            trigger={
              <Paziresh24Button
                children2={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a5F0I
                    )}
                  >
                    {"\u0646\u0648\u0634\u062a\u0646 \u0646\u0638\u0631"}
                  </div>
                }
                className={classNames(
                  "__wab_instance",
                  sty.paziresh24Button___9ByF
                )}
                showStartIcon={true}
                size={"compact"}
                startIcon={
                  <LauncherIconsEditIcon
                    className={classNames(projectcss.all, sty.svg___2K9VH)}
                    role={"img"}
                  />
                }
              />
            }
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__pvpPr)}>
          {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
            (() => {
              try {
                return [5, 4, 3, 2, 1];
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()
          ).map((__plasmic_item_0, __plasmic_idx_0) => {
            const currentItem = __plasmic_item_0;
            const currentIndex = __plasmic_idx_0;
            return (
              <LauncherBlocksRateRow
                data-plasmic-name={"launcherBlocksRateRow"}
                data-plasmic-override={overrides.launcherBlocksRateRow}
                className={classNames(
                  "__wab_instance",
                  sty.launcherBlocksRateRow
                )}
                currentItem={currentItem}
                key={currentIndex}
                percentage={(() => {
                  try {
                    return $state.apiRequest4.data?.count
                      ? ($state.apiRequest4.data[currentItem] /
                          $state.apiRequest4.data?.count) *
                          100
                      : 0;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return 60;
                    }
                    throw e;
                  }
                })()}
              />
            );
          })}
        </div>
        <ApiRequest
          data-plasmic-name={"apiRequest4"}
          data-plasmic-override={overrides.apiRequest4}
          children={null}
          className={classNames("__wab_instance", sty.apiRequest4)}
          errorDisplay={null}
          loadingDisplay={null}
          method={"GET"}
          onError={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["apiRequest4", "error"]).apply(
              null,
              eventArgs
            );
          }}
          onLoading={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["apiRequest4", "loading"]).apply(
              null,
              eventArgs
            );
          }}
          onSuccess={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["apiRequest4", "data"]).apply(
              null,
              eventArgs
            );
          }}
          ref={ref => {
            $refs["apiRequest4"] = ref;
          }}
          url={(() => {
            try {
              return `https://apigw.paziresh24.com/v1/hamdast/apps/${$props.appKey}/rates`;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        />
      </div>
      <ApiRequest
        data-plasmic-name={"apiRequest3"}
        data-plasmic-override={overrides.apiRequest3}
        className={classNames("__wab_instance", sty.apiRequest3)}
        errorDisplay={null}
        loadingDisplay={
          <LauncherIconsLoaderIcon
            className={classNames(projectcss.all, sty.svg__ylqd5)}
            role={"img"}
          />
        }
        method={"GET"}
        onError={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiRequest3", "error"]).apply(
            null,
            eventArgs
          );
        }}
        onLoading={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiRequest3", "loading"]).apply(
            null,
            eventArgs
          );
        }}
        onSuccess={async (...eventArgs: any) => {
          generateStateOnChangeProp($state, ["apiRequest3", "data"]).apply(
            null,
            eventArgs
          );
        }}
        params={{ limit: 3 }}
        ref={ref => {
          $refs["apiRequest3"] = ref;
        }}
        url={(() => {
          try {
            return `https://apigw.paziresh24.com/v1/hamdast/apps/${$props.appKey}/reviews`;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      >
        {(() => {
          try {
            return $state.apiRequest3.data?.length > 0;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })()
          ? (_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return $state.apiRequest3.data;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <LauncherBlocksReviewCard
                  appKey={(() => {
                    try {
                      return $props.appKey;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  className={classNames(
                    "__wab_instance",
                    sty.launcherBlocksReviewCard__sx0Of
                  )}
                  content={(() => {
                    try {
                      return currentItem.content;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  createdAt={(() => {
                    try {
                      return currentItem.created_at;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  id={(() => {
                    try {
                      return currentItem.id;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  key={currentIndex}
                  rate={(() => {
                    try {
                      return currentItem.rate;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                  userId={(() => {
                    try {
                      return currentItem.user_id;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />
              );
            })
          : null}
        {(() => {
          try {
            return !$state.apiRequest3.data;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <LauncherIconsLoaderIcon
            className={classNames(projectcss.all, sty.svg__miJs)}
            role={"img"}
          />
        ) : null}
        {(() => {
          try {
            return (
              !!$state.apiRequest3?.data &&
              $state?.apiRequest3?.data?.length == 0
            );
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__t4F3X
            )}
          >
            {
              "\u0647\u0646\u0648\u0632 \u0646\u0638\u0631\u06cc \u062b\u0628\u062a \u0646\u0634\u062f\u0647. \u0627\u0648\u0644\u06cc\u0646 \u0646\u0641\u0631 \u0628\u0627\u0634!\r"
            }
          </div>
        ) : null}
      </ApiRequest>
      {(() => {
        try {
          return (
            $state.apiRequest4.data.count - 3 > 0 &&
            $state.apiRequest3?.data?.length > 0
          );
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return false;
          }
          throw e;
        }
      })() ? (
        <Paziresh24Modal
          data-plasmic-name={"modal"}
          data-plasmic-override={overrides.modal}
          body={
            <React.Fragment>
              <ApiRequest
                data-plasmic-name={"apiRequest"}
                data-plasmic-override={overrides.apiRequest}
                children={null}
                className={classNames("__wab_instance", sty.apiRequest)}
                errorDisplay={null}
                loadingDisplay={null}
                method={"GET"}
                onError={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "apiRequest",
                    "error"
                  ]).apply(null, eventArgs);
                }}
                onLoading={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "apiRequest",
                    "loading"
                  ]).apply(null, eventArgs);
                }}
                onSuccess={async (...eventArgs: any) => {
                  generateStateOnChangeProp($state, [
                    "apiRequest",
                    "data"
                  ]).apply(null, eventArgs);

                  (async data => {
                    const $steps = {};

                    $steps["updateReviews"] =
                      $state.apiRequest.data?.length > 0
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["reviews"]
                              },
                              operation: 0,
                              value: [
                                ...$state.reviews,
                                ...$state.apiRequest.data
                              ]
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                    if (
                      $steps["updateReviews"] != null &&
                      typeof $steps["updateReviews"] === "object" &&
                      typeof $steps["updateReviews"].then === "function"
                    ) {
                      $steps["updateReviews"] = await $steps["updateReviews"];
                    }
                  }).apply(null, eventArgs);
                }}
                params={(() => {
                  try {
                    return {
                      limit: 10,
                      page: $state.page
                    };
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
                ref={ref => {
                  $refs["apiRequest"] = ref;
                }}
                url={(() => {
                  try {
                    return `https://apigw.paziresh24.com/v1/hamdast/apps/${$props.appKey}/reviews`;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return undefined;
                    }
                    throw e;
                  }
                })()}
              />

              {(() => {
                try {
                  return $state.reviews?.length == 0;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <LauncherIconsLoaderIcon
                  className={classNames(projectcss.all, sty.svg__ltJ27)}
                  role={"img"}
                />
              ) : null}
              {(() => {
                try {
                  return $state.reviews?.length > 0;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox___3U7Mx)}
                >
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return $state.reviews;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <LauncherBlocksReviewCard
                        appKey={(() => {
                          try {
                            return $props.appKey;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        className={classNames(
                          "__wab_instance",
                          sty.launcherBlocksReviewCard__lvQ5F
                        )}
                        content={(() => {
                          try {
                            return currentItem.content;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        createdAt={(() => {
                          try {
                            return currentItem.created_at;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        id={(() => {
                          try {
                            return currentItem.id;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        key={currentIndex}
                        rate={(() => {
                          try {
                            return currentItem.rate;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                        userId={(() => {
                          try {
                            return currentItem.user_id;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                      />
                    );
                  })}
                  {(() => {
                    try {
                      return (
                        $state.reviews?.length < $state.apiRequest4?.data?.count
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return true;
                      }
                      throw e;
                    }
                  })() ? (
                    <Paziresh24Button
                      children2={
                        "\u0645\u0634\u0627\u0647\u062f\u0647 \u0628\u06cc\u0634\u062a\u0631"
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.paziresh24Button___5GPji
                      )}
                      loading={(() => {
                        try {
                          return (
                            $state.reviews > 0 && $state.apiRequest?.loading
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return [];
                          }
                          throw e;
                        }
                      })()}
                      onClick={async event => {
                        const $steps = {};

                        $steps["updatePage"] = true
                          ? (() => {
                              const actionArgs = {
                                variable: {
                                  objRoot: $state,
                                  variablePath: ["page"]
                                },
                                operation: 2
                              };
                              return (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                const oldValue = $stateGet(
                                  objRoot,
                                  variablePath
                                );
                                $stateSet(objRoot, variablePath, oldValue + 1);
                                return oldValue + 1;
                              })?.apply(null, [actionArgs]);
                            })()
                          : undefined;
                        if (
                          $steps["updatePage"] != null &&
                          typeof $steps["updatePage"] === "object" &&
                          typeof $steps["updatePage"].then === "function"
                        ) {
                          $steps["updatePage"] = await $steps["updatePage"];
                        }
                      }}
                      outline={true}
                      size={"compact"}
                    />
                  ) : null}
                </div>
              ) : null}
            </React.Fragment>
          }
          className={classNames("__wab_instance", sty.modal)}
          onOpenChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["modal", "open"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }

            (async val => {
              const $steps = {};

              $steps["updateReviews"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["reviews"]
                      },
                      operation: 0,
                      value: []
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateReviews"] != null &&
                typeof $steps["updateReviews"] === "object" &&
                typeof $steps["updateReviews"].then === "function"
              ) {
                $steps["updateReviews"] = await $steps["updateReviews"];
              }

              $steps["updatePage"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["page"]
                      },
                      operation: 0,
                      value: 1
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updatePage"] != null &&
                typeof $steps["updatePage"] === "object" &&
                typeof $steps["updatePage"].then === "function"
              ) {
                $steps["updatePage"] = await $steps["updatePage"];
              }
            }).apply(null, eventArgs);
          }}
          open={generateStateValueProp($state, ["modal", "open"])}
          title={
            "\u0646\u0638\u0631\u0627\u062a \u06a9\u0627\u0631\u0628\u0631\u0627\u0646\r"
          }
          trigger={
            (() => {
              try {
                return (
                  $state.apiRequest4.data.count - 3 > 0 &&
                  $state.apiRequest3?.data?.length > 0
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return true;
                }
                throw e;
              }
            })() ? (
              <Paziresh24Button
                children2={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jfExx
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "\u0645\u0634\u0627\u0647\u062f\u0647 \u0628\u06cc\u0634\u062a\u0631 "
                        }
                      </React.Fragment>
                      {
                        <span
                          data-plasmic-name={"span"}
                          data-plasmic-override={overrides.span}
                          className={classNames(
                            projectcss.all,
                            projectcss.span,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.span
                          )}
                        >
                          <React.Fragment>
                            <React.Fragment>{"("}</React.Fragment>
                            {
                              <strong
                                data-plasmic-name={"strong"}
                                data-plasmic-override={overrides.strong}
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  projectcss.plasmic_default__inline,
                                  sty.strong
                                )}
                              >
                                <React.Fragment>
                                  {(() => {
                                    try {
                                      return (
                                        $state.apiRequest4?.data?.count - 3
                                      );
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return "1";
                                      }
                                      throw e;
                                    }
                                  })()}
                                </React.Fragment>
                              </strong>
                            }
                            <React.Fragment>
                              {" \u0646\u0638\u0631 \u062f\u06cc\u06af\u0631)"}
                            </React.Fragment>
                          </React.Fragment>
                        </span>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                }
                className={classNames(
                  "__wab_instance",
                  sty.paziresh24Button__blmzN
                )}
                outline={true}
                size={"compact"}
              />
            ) : null
          }
        />
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "modal2",
    "launcherBlocksWriteReview",
    "launcherBlocksRateRow",
    "apiRequest4",
    "apiRequest3",
    "modal",
    "span",
    "strong",
    "apiRequest"
  ],
  modal2: ["modal2", "launcherBlocksWriteReview"],
  launcherBlocksWriteReview: ["launcherBlocksWriteReview"],
  launcherBlocksRateRow: ["launcherBlocksRateRow"],
  apiRequest4: ["apiRequest4"],
  apiRequest3: ["apiRequest3"],
  modal: ["modal", "span", "strong", "apiRequest"],
  span: ["span", "strong"],
  strong: ["strong"],
  apiRequest: ["apiRequest"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  modal2: typeof Paziresh24Modal;
  launcherBlocksWriteReview: typeof LauncherBlocksWriteReview;
  launcherBlocksRateRow: typeof LauncherBlocksRateRow;
  apiRequest4: typeof ApiRequest;
  apiRequest3: typeof ApiRequest;
  modal: typeof Paziresh24Modal;
  span: "span";
  strong: "strong";
  apiRequest: typeof ApiRequest;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLauncherBlocksRateReview__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLauncherBlocksRateReview__VariantsArgs;
    args?: PlasmicLauncherBlocksRateReview__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicLauncherBlocksRateReview__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLauncherBlocksRateReview__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLauncherBlocksRateReview__ArgProps,
          internalVariantPropNames:
            PlasmicLauncherBlocksRateReview__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLauncherBlocksRateReview__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLauncherBlocksRateReview";
  } else {
    func.displayName = `PlasmicLauncherBlocksRateReview.${nodeName}`;
  }
  return func;
}

export const PlasmicLauncherBlocksRateReview = Object.assign(
  // Top-level PlasmicLauncherBlocksRateReview renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    modal2: makeNodeComponent("modal2"),
    launcherBlocksWriteReview: makeNodeComponent("launcherBlocksWriteReview"),
    launcherBlocksRateRow: makeNodeComponent("launcherBlocksRateRow"),
    apiRequest4: makeNodeComponent("apiRequest4"),
    apiRequest3: makeNodeComponent("apiRequest3"),
    modal: makeNodeComponent("modal"),
    span: makeNodeComponent("span"),
    strong: makeNodeComponent("strong"),
    apiRequest: makeNodeComponent("apiRequest"),

    // Metadata about props expected for PlasmicLauncherBlocksRateReview
    internalVariantProps: PlasmicLauncherBlocksRateReview__VariantProps,
    internalArgProps: PlasmicLauncherBlocksRateReview__ArgProps
  }
);

export default PlasmicLauncherBlocksRateReview;
/* prettier-ignore-end */
