version: '3.7'

services:
  patient-app:
    container_name: patient-app
    image: dockerhub.paziresh24.com/patient-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9080:3000
    restart: always
