export const popularCities = [
  {
    id: '-1',
    name: 'همه ایران',
    en_slug: 'ir',
  },
  {
    id: '117',
    province_id: '8',
    name: 'تهران',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'tehran',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '60',
    province_id: '4',
    name: 'اصفهان',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'isfahan',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '232',
    province_id: '17',
    name: 'شیراز',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'shiraz',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '153',
    province_id: '11',
    name: 'مشهد',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'mashhad',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '283',
    province_id: '5',
    name: 'کرج',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'karaj',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '311',
    province_id: '22',
    name: 'کرمانشاه',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'kermanshah',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '418',
    province_id: '30',
    name: 'همدان',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'hamedan',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '179',
    province_id: '13',
    name: 'اهواز',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'ahvaz',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '1',
    province_id: '1',
    name: 'تبریز',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'tabriz',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '403',
    province_id: '29',
    name: 'بندرعباس',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'bandar-abbas',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '274',
    province_id: '19',
    name: 'قم',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'qom',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
  {
    id: '426',
    province_id: '31',
    name: 'یزد',
    insert_at: '0',
    last_update: '0',
    delete: '0',
    en_slug: 'yazd',
    created_by: null,
    updated_by: null,
    is_capital: '1',
  },
];
