// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPaziresh24AtomsDescription,
  DefaultPaziresh24AtomsDescriptionProps
} from "./plasmic/paziresh_24_design_system/PlasmicPaziresh24AtomsDescription";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface Paziresh24AtomsDescriptionProps extends Omit<DefaultPaziresh24AtomsDescriptionProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPaziresh24AtomsDescriptionProps altogether and have
// total control over the props for your component.
export interface Paziresh24AtomsDescriptionProps
  extends DefaultPaziresh24AtomsDescriptionProps {}

function Paziresh24AtomsDescription(props: Paziresh24AtomsDescriptionProps) {
  // Use PlasmicPaziresh24AtomsDescription to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicPaziresh24AtomsDescription are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Paziresh24AtomsDescriptionProps here, but feel free
  // to do whatever works for you.

  return <PlasmicPaziresh24AtomsDescription {...props} />;
}

export default Paziresh24AtomsDescription;
