/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 85GFtqPAFvUkDYJxzFDEYS

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantskyNbKHd2ZL } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: KYNb-K-Hd2zL/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantskyNbKHd2ZL
});
