/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 666TdydnqTmUJpihDvjWrt

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_9GOjxm7I0Api } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9gOjxm7I0API/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_9GOjxm7I0Api
});
