name: Trigger GitLab CI
permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  sync-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Force GitLab Mirror Sync
        run: |
          curl --request POST \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
            "https://hamgit.ir/api/v4/projects/17768/mirror/pull"
          sleep 15

      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
            --form token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            --form ref=main \
            "https://hamgit.ir/api/v4/projects/17768/trigger/pipeline"
