name: Auto-remove Google Fonts on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  clean-fonts:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run cleanup script
        run: |
          chmod +x ./remove-google-fonts.sh
          ./remove-google-fonts.sh

      - name: Commit changes if needed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "chore: remove Google Fonts imports automatically"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
